# Generated by Django 4.1.7 on 2023-03-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingsite', '0002_rename_user_game_user_id_alter_game_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gametype',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
